FROM ubuntu:22.04

RUN apt-get update && \
  apt-get install -y git curl unzip build-essential && \
  apt-get clean -y && \
  curl -fsSL https://deno.land/x/install/install.sh | sh && \
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
  bash -c ". /root/.nvm/nvm.sh && nvm install node && nvm alias default node"

ENV DENO_INSTALL="/root/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"

WORKDIR /workdir

