name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Run tests
        env:
          LOTR_API_TOKEN: "${{ secrets.LOTR_API_TOKEN }}"
        run: |
          deno --version
          deno fmt --ignore=deno_dir --check
          DEBUG=true deno test --lock=lock.json --allow-none --allow-env --unstable
          DEBUG=true RUN_INTEGRATION_TESTS=true deno test --lock=lock.json --allow-none --allow-env --unstable  --allow-net